language: java

sudo: required # So we can use docker and a beefier machine
dist: trusty

git:
  depth: 1 # an optimization since we won't be committing anything
  quiet: true

services:
- mysql
- postgresql
- docker # In order to run other DBMS such as DB2

stages:
- compile
- test
- deploy

jobs:
  include:
  - stage: compile

    before_install:
    - source .travisci/setup.sh
    install: mvn package -DskipTests=true -Dmaven.javadoc.skip=true -V -B
    script: mvn test -Dtest=!MySQLMigrationSpec,!org.javalite.db_migrator.* -DfailIfNoTests=false -V

  - stage: test
    # ----------------------- mysql -----------------------
    env: DB=mysql_travis-ci
    before_install:
    - source .travisci/setup.sh
    before_script:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
    script:
    - echo "Starting MySQL build"
    - cd activejdbc
    - echo "mvn test -P$DB -V -B" && mvn test -P$DB -V -B

  - # --------------------- postgresql ---------------------
    env: DB=postgresql_travis-ci
    before_install:
    - source .travisci/setup.sh
    before_script:
    - psql -c 'create database test;' -U postgres
    script:
    - echo "Starting PostgreSQL build"
    - cd activejdbc
    - echo "mvn test -P$DB -V -B" && mvn test -P$DB -V -B

  - # ----------------------- db2 -----------------------
    env: DB=db2_travis-ci
    before_install:
    - source .travisci/setup.sh
    - docker run -d -p 50000:50000 --name db2 -e DB2INST1_PASSWORD=dzqAbmZwnN8c -e LICENSE=accept ibmcom/db2express-c:latest db2start
    - docker ps # db2 takes a sec to start before we can issue the db creation
    - docker exec -u db2inst1 -it db2 /bin/bash -c ". /home/db2inst1/sqllib/db2profile && db2 create db db2 && exit"
    script:
    - echo "Starting DB2 build"
    - cd activejdbc
    - echo "mvn test -P$DB -V -B" && mvn test -P$DB -V -B

  - # ----------------------- mssql -----------------------
    env: DB=mssql_travis-ci
    before_install:
    - source .travisci/setup.sh
    - docker run -e ACCEPT_EULA=Y -e SA_PASSWORD=CVXQj6sC9D3s3PzE! -e MSSQL_PID=Express -p 1433:1433 --name mssql_active-jdbc -d microsoft/mssql-server-linux:latest
    - docker ps
    script:
    - echo "Starting MS SQLServer build"
    - cd activejdbc
    - echo "mvn test -P$DB -V -B" && mvn test -P$DB -V -B

  - # ----------------------- sqlite -----------------------
    env: DB=sqlite_travis-ci
    before_install:
    - source .travisci/setup.sh
    script:
    - echo "Starting SQLite build"
    - cd activejdbc
    - echo "mvn test -P$DB -V -B" && mvn test -P$DB -V -B

    # ->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->
    #                      Deploy Stage
    # ->->->->->->->->->->->->->->->->->->->->->->->->->->->->->->
  - stage: deploy
    # TODO require the branch name to be master (note for PRs this is the base branch name)
    if: |
      repo = javalite/activejdbc AND \
      branch = issue_752

    before_install:
    - source .travisci/setup.sh
    script: sh $TRAVIS_BUILD_DIR/.travisci/deploy.sh